services:
  db:
    image: postgres:16-alpine
    container_name: students-api-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: studentsdb
      POSTGRES_USER: studentsapi
      POSTGRES_PASSWORD: studentsapi

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studentsapi -d studentsdb"]
      interval: 5s
      retries: 10

volumes:
  pgdata:
