spring.application.name=students-api

# ---- PostgreSQL ----
spring.datasource.url=jdbc:postgresql://studentsdb_fa03_user:DdZSLnDQDrMdasTjjkWwCNbP2WNtGVDg@dpg-d95fp77avr4c73abcfbg-a.oregon-postgres.render.com/studentsdb_fa03
spring.datasource.username=studentsdb_fa03_user
spring.datasource.password=DdZSLnDQDrMdasTjjkWwCNbP2WNtGVDg
spring.datasource.driver-class-name=org.postgresql.Driver

# ---- JPA / Hibernate ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ---- Swagger / OpenAPI ----
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

